server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: matchmaking
          uri: lb://MATCHMAKING-SERVICE
          predicates:
            - Path=/api/matchmaking/**
          filters:
            - JwtValidationFilter

        - id: game
          uri: lb:ws://GAME-SERVICE
          predicates:
            - Path=/ws/game/**
          filters:
            - JwtValidationFilter
            - GameRoutingFilter

        - id: ratings
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**

        - id: history
          uri: lb://HISTORY-SERVICE
          predicates:
            - Path=/api/history/**

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
